### ISSUE TITLE
Mejorar la búsqueda de asesor

### ISSUE THREAD

**Issue by Raynou** [adielmtz/TECNM-Residencias#1]
Cuando se busca algún asesor interno por su apellido la interfaz no hace autocompletado, solo funciona con su nombre de pila. Esto es un problema ya que hay docentes que se les identifica más por su apellido (e.g. Berlanga, Peralta, Hilario)

**Comment by adielmtz** [comment]
![Imagen de WhatsApp 2024-09-12 a las 12 10 19_9b1f4b8c](https://github.com/user-attachments/assets/95837251-61ce-4612-b521-85a24a301efa)

También es necesario revisar que este error no esté presente luego de actualizar el mecanismo para seleccionar los asesores.

**Comment by Raynou** [comment]
Según el usuario:

"Sale error cuando no se asigna asesor externo cuando no está especificado en el protocolo"
