### ISSUE TITLE
[BUG] El sistema no contempla la eliminación de archivos no existentes

### ISSUE THREAD

**Issue by Raynou** [adielmtz/TECNM-Residencias#18]
Se puede dar el caso de que alguien borre intencional/accidentalmente un archivo (e.g La constancia de servicio social) de un alumno, en dado caso, el sistema no permitirá eliminar el archivo del expediente del alumno en la GUI.

Pasos para replicar el error:

1. Agregar documentos a un expediente (existente o nuevo)
2. Ir manualmente a borrar algún documento de ese expediente en particular (por ejemplo, la constancia de servicio social)
3. Regresar al sistema y checar el expediente del que se borró un archivo

Al hacer esto se podrá observar como la constancia de servicio social sigue listada en los archivos del expediente, aunque esta ya no existe dentro del sistema de archivos, no se le permitirá al usuario borrarla ni abrirla.

**Comment by Raynou** [comment]
![image](https://github.com/user-attachments/assets/7c325130-9c16-4620-b25b-7408e31749dd)

![image](https://github.com/user-attachments/assets/72c270d8-5bf0-470c-97fc-cce906dbd6db)

**Comment by adielmtz** [comment]
Esto es esperado, por eso los try-catch. En ese punto, no hay nada que realmente se pueda hacer para manejar la excepción.
